interface NarrativeSummaryProps {
  summary: string;
}

export default function NarrativeSummary({ summary }: NarrativeSummaryProps) {
  return (
    <div className="bg-blue-50 border border-blue-200 rounded-xl p-5 space-y-2">
      <div className="flex items-center gap-2">
        <span className="text-blue-700 font-medium text-sm">Your Health Summary</span>
        <span className="text-blue-400 text-xs">Generated by AI · Not medical advice</span>
      </div>
      <p className="text-blue-900 text-sm leading-relaxed">{summary}</p>
    </div>
  );
}
